name: Build & Test

on:
  workflow_call:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "repo"
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Website Dependencies
        working-directory: repo/website
        run: npm ci
      - name: Install Documentation Dependencies
        working-directory: repo/documentation
        run: npm ci
      - name: Install Extension Dependencies
        working-directory: repo/extension
        run: npm ci
      - name: Lint Website Source
        working-directory: repo/website
        run: npm run lint
      - name: Build Website
        working-directory: repo/website
        run: npm run build
      - name: Build Documentation
        working-directory: repo/documentation
        run: npm run build
      - name: Lint Extension Source
        working-directory: repo/extension
        run: npm run lint
      - name: Test Extension
        working-directory: repo/extension
        run: npm run test
      - name: Build Extension
        working-directory: repo/extension
        run: npm run build
      - name: Create build output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            repo/documentation/dist/
            repo/extension/dist/
            repo/extension/coverage/
            repo/website/dist/
