name: Build & Publish

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  commit-hash:
    name: Get the commit hash
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.set-commit-hash.outputs.FE_SHORT_COMMIT_HASH }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'
          fetch-depth: 0
      - name: Get Short Commit Hash
        id: set-commit-hash
        working-directory: repo
        run: |
          FE_SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Short commit hash is $FE_SHORT_COMMIT_HASH"
          echo "FE_SHORT_COMMIT_HASH=$FE_SHORT_COMMIT_HASH" >> $GITHUB_OUTPUT
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yml
    needs: commit-hash
    with:
      commit-hash: ${{ needs.commit-hash.outputs.commit-hash }}
  publish-documentation:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build/
      - name: Checkout Wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          ref: 'master'
          token: '${{ secrets.SERVICE_PAT }}'
          path: 'wiki'
      - name: Remove Existing Wiki Contents
        working-directory: wiki
        run: |
          git rm -rf .
          git clean -fxd
      - name: Copy Documentation Folder to Wiki
        run: cp -R build/documentation/dist/* wiki/
      - name: Stage Wiki
        working-directory: wiki
        run: git add -A
      - name: Commit Wiki
        working-directory: wiki
        run: |
          git config --global user.email "financialenforcerapp@gmail.com"
          git config --global user.name "Financial Enforcer Service Account"
          git commit -m "Wiki for $GITHUB_SHA"
      - name: Push Wiki
        working-directory: wiki
        run: git push origin master
  publish-website:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build/
      - uses: actions/checkout@v3
        with:
          path: 'repo'
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Checkout GH Pages
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          token: '${{ secrets.SERVICE_PAT }}'
          path: 'gh-pages'
      - name: Remove Existing Docs Directory
        working-directory: gh-pages
        run: rm -rf docs
      - name: Create Docs Directory
        working-directory: gh-pages
        run: mkdir -p docs
      - name: Create CNAME File
        working-directory: gh-pages
        run: echo 'www.financialenforcer.com' > docs/CNAME
      - name: Copy Distribution Folder to Docs
        run: cp -R build/website/dist/* gh-pages/docs/
      - name: Create Version Text File
        run: |
          echo "$GITHUB_SHA" > gh-pages/docs/version.txt
          echo "This wiki was built from $GITHUB_SHA" > wiki/Version.md
          echo "$GITHUB_SHA" > build/extension/dist/version.txt
      - name: ZIP Extension
        working-directory: repo/extension
        run: |
          FE_LONG_COMMIT_HASH=$(git rev-parse HEAD)
          echo "Long commit hash is $FE_LONG_COMMIT_HASH"
          echo "FE_LONG_COMMIT_HASH=$FE_LONG_COMMIT_HASH" >> $GITHUB_ENV

          npm run package ${{ needs.commit-hash.outputs.commit-hash }}

          FE_ZIP_NAME=$(ls financial-enforcer-*.zip)
          echo "ZIP name is $FE_ZIP_NAME"
          echo "FE_ZIP_NAME=$FE_ZIP_NAME" >> $GITHUB_ENV

          FE_TAG=$(echo "$FE_ZIP_NAME" | sed 's/.*-\([0-9\.]*-[^\.]*\)\..*/\1/')
          echo "Tag is $FE_TAG"
          echo "FE_TAG=$FE_TAG" >> $GITHUB_ENV
      - name: Copy Extension to Docs
        run: cp repo/extension/financial-enforcer-*.zip gh-pages/docs/financial-enforcer.zip
      - name: Stage Pages
        working-directory: gh-pages/docs
        run: git add -A
      - name: Commit Pages
        working-directory: gh-pages
        run: |
          git config --global user.email "financialenforcerapp@gmail.com"
          git config --global user.name "Financial Enforcer Service Account"
          git commit -m "Pages for $GITHUB_SHA"
      - name: Push Pages
        working-directory: gh-pages
        run: git push origin gh-pages
      - name: 'Upload ZIP as Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: 'repo/extension/${{ env.FE_ZIP_NAME }}'
          retention-days: 90
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: 'See the commit hash for information.'
          token: ${{ secrets.SERVICE_PAT }}
          tag_name: '${{ env.FE_TAG }}'
          target_commitish: '${{ env.FE_LONG_COMMIT_HASH }}'
          name: '${{ env.FE_TAG }}'
          files: 'repo/extension/${{ env.FE_ZIP_NAME }}'
        env:
          GITHUB_REPOSITORY: FinancialEnforcer/financial-enforcer
