name: PR Validation

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "repo"
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Website Dependencies
        working-directory: repo/website
        run: npm install
      - name: Lint Website Source
        working-directory: repo/website
        run: npm run lint
      - name: Build Website
        working-directory: repo/website
        run: npm run build
      - name: Install Extension Dependencies
        working-directory: repo/extension
        run: npm install
      - name: Lint Extension Source
        working-directory: repo/extension
        run: npm run lint
      - name: Test Extension
        working-directory: repo/extension
        run: npm run test
      - name: Report Coverage
        working-directory: repo/extension
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
      - name: Build Extension
        working-directory: repo/extension
        run: npm run build
