name: Security

on:
  workflow_call:

jobs:
  security:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
      - name: Snyk Scan
        uses: snyk/actions/node@master
        with:
          args: 'repo/extension repo/website repo/documentation'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
